"""Constants for the Fashion MNIST and Digits MNIST datasets."""

FASHION_MNIST_INPUT_DIM = 784
FASHION_MNIST_OUTPUT_DIM = 10

DIGITS_MNIST_INPUT_DIM = 784
DIGITS_MNIST_OUTPUT_DIM = 10

FASHION_MNIST_MEAN = 0.286
FASHION_MNIST_STD = 0.353
MNIST_DIGITS_MEAN = 0.1307
MNIST_DIGITS_STD = 0.3081
